---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: greeting-producer
- name: current-app-info

run:
  path: greeting-producer/ci/tasks/bg-upgrade.sh
