---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: tkaburagi/sc-demo
    tag: "latest"

inputs:
  - name: greeting-producer
  - name: current-app-info

outputs:
  - name: app-manifest-output

run:
  path: greeting-producer/ci/tasks/editmanifest.sh