---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: greeting-producer

outputs:
  - name: current-app-info

caches:
  - path: repo/m2

run:
  path: sh
  args:
    - greeting-producer/ci/tasks/build.sh