---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8-jre-alpine    
inputs:
  - name: greeting-producer

run:
  path: greeting-producer/ci/tasks/integration.sh
