---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: tkaburagi/sc-demo
    tag: "latest"

inputs:
  - name: m2
  - name: greeting-producer
run:
  path: greeting-producer/ci/tasks/integration.sh
