---
platform: linux
#image_resource:
#  type: docker-image
#  source:
#    repository: java
#    tag: openjdk-8-jdk-alpine

image_resource: &maven-image
   type: docker-image
   source:
    repository: maven
    tag: alpine

inputs:
  - name: maven-cache
  - name: greeting-producer
run:
  path: greeting-producer/ci/tasks/integration.sh
