---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: tkaburagi/sc-demo
    tag: "latest"

inputs:
  - name: m2
  - name: greeting-producer

caches:
  - path: repo/m2

run:
  path: greeting-producer/ci/tasks/integration.sh
