---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: appropriate/curl
    tag: "latest"

inputs:
  - name: greeting-producer

run:
  path: greeting-producer/ci/tasks/smoke.sh