---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: greeting-producer
  - name: m2
run:
# dir: maven-repo
  path: greeting-producer/ci/tasks/unit.sh
